version: "3.9"

services:
  react_todo_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_todo_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true   # Fix hot reload in Docker

